version: '{build}'
image: Visual Studio 2019
configuration: Release
environment:
  ASPNETCORE_ENVIRONMENT: Staging
deploy: off
branches:
  only:
    - develop
    - /release.*/ 
    - master
skip_commits:
  files:
  - LICENSE
  - README.md
  - .travis.yml
  - WebInfrastructure.sln.DotSettings
services: mssql2017  
install:
      - ps: choco install rabbitmq --version 3.7.7 -y
build_script:
      - ps: >-
          cd build

          .\build.ps1 -target Test --settings_skipverification=true
